Log:
    Level: error # Log level: none, error, warning, info, debug 
    AccessPath: # ./access.Log
    ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json Path to dns config, check https://xtls.github.io/config/base/dns/ for help
RouteConfigPath: # ./route.json # Path to route config, check https://xtls.github.io/config/base/route/ for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # ./custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/base/outbound/ for help
ConnetionConfig:
    Handshake: 4 # Handshake time limit, Second
    ConnIdle: 10 # Connection idle time limit, Second
    UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
    DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
    BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
    -
        PanelType: "V2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel
        ApiConfig:
            ApiHost: "https://xx.xx.xx"
            ApiKey: "xx"
            NodeID: "3"
            NodeType: "V2ray" # Node type: V2ray, Trojan, Shadowsocks, Shadowsocks-Plugin
            Timeout: 30 # Timeout for the api request
            EnableVless: false # Enable Vless for V2ray Type
            EnableXTLS: false # Enable XTLS for V2ray and Trojan
            SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
            DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
            RuleListPath:  # ./rulelist Path to local rulelist file
        ControllerConfig:
            ListenIP: 127.0.0.1 # IP address you want to listen
            SendIP: 0.0.0.0 # IP address you want to send pacakage
            UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
            EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
            DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
            DisableUploadTraffic: false # Disable Upload Traffic to the panel
            DisableGetRule: false # Disable Get Rule from the panel
            DisableIVCheck: false # Disable the anti-reply protection for Shadowsocks 
            EnableProxyProtocol: false # Only works for WebSocket and TCP
            EnableFallback: true # Only support for Trojan and Vless
            FallBackConfigs: # Support multiple fallbacks
                -
                    SNI: # TLS SNI(Server Name Indication), Empty for any
                    Path: # HTTP PATH, Empty for any
                    Dest: "80" # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
                    ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
            CertConfig:
                CertMode: "none" # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
                CertDomain: "v3.nlist.xyz" # Domain to cert
                CertFile: "/srv/.cert/v3.nlist.xyz.crt" # Provided if the CertMode is file
                KeyFile: "/srv/.cert/v3.nlist.xyz.key" # http default in /etc/XrayR/cert/certificates/
                Email: "admin@nlist.xyz"
    -
        PanelType: "V2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel
        ApiConfig:
            ApiHost: "https://xx.xx.xx"
            ApiKey: "xx"
            NodeID: "3"
            NodeType: "Trojan" # Node type: V2ray, Trojan, Shadowsocks, Shadowsocks-Plugin
            Timeout: 30 # Timeout for the api request
            EnableVless: false # Enable Vless for V2ray Type
            EnableXTLS: false # Enable XTLS for V2ray and Trojan
            SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
            DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
            RuleListPath: "/etc/XrayR/rulelist" # ./rulelist Path to local rulelist file
        ControllerConfig:
            ListenIP: 127.0.0.1 # IP address you want to listen
            SendIP: 0.0.0.0 # IP address you want to send pacakage
            UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
            EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
            DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
            DisableUploadTraffic: false # Disable Upload Traffic to the panel
            DisableGetRule: false # Disable Get Rule from the panel
            DisableIVCheck: false # Disable the anti-reply protection for Shadowsocks 
            EnableProxyProtocol: true # Only works for WebSocket and TCP
            EnableFallback: true # Only support for Trojan and Vless
            FallBackConfigs: # Support multiple fallbacks
                -
                    SNI: # TLS SNI(Server Name Indication), Empty for any
                    Path: # HTTP PATH, Empty for any
                    Dest: "80" # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
                    ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
            CertConfig:
                CertMode: "file" # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
                CertDomain: "t3.nlist.xyz" # Domain to cert
                CertFile: "/srv/.cert/t3.nlist.xyz.crt" # Provided if the CertMode is file
                KeyFile: "/srv/.cert/t3.nlist.xyz.key" # http default in /etc/XrayR/cert/certificates/
                Email: "admin@nlist.xyz"
